/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Imagen;

/**
 *
 * @author sam
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_fondo = new javax.swing.JPanel();
        txt_texto = new javax.swing.JTextField();
        lbl_mensaje = new javax.swing.JLabel();
        btn_ingresar = new javax.swing.JButton();
        lbl_comprobado = new javax.swing.JLabel();
        pn_barra = new javax.swing.JPanel();
        lbl_cerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        pn_fondo.setBackground(new java.awt.Color(254, 254, 254));
        pn_fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_texto.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        txt_texto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pn_fondo.add(txt_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 164, 356, 44));

        lbl_mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pn_fondo.add(lbl_mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 420, 46));

        btn_ingresar.setBackground(new java.awt.Color(55, 68, 166));
        btn_ingresar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_ingresar.setForeground(new java.awt.Color(254, 254, 254));
        btn_ingresar.setText("Ingresar");
        btn_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_fondo.add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 573, 102, 44));

        lbl_comprobado.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        lbl_comprobado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pn_fondo.add(lbl_comprobado, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 500, 430, 43));

        pn_barra.setBackground(new java.awt.Color(0, 102, 204));

        lbl_cerrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cerrar.setText("X");
        lbl_cerrar.setToolTipText("cerrar");
        lbl_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pn_barraLayout = new javax.swing.GroupLayout(pn_barra);
        pn_barra.setLayout(pn_barraLayout);
        pn_barraLayout.setHorizontalGroup(
            pn_barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_barraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pn_barraLayout.setVerticalGroup(
            pn_barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_barraLayout.createSequentialGroup()
                .addComponent(lbl_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pn_fondo.add(pn_barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 742, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_ingresar;
    public javax.swing.JLabel lbl_cerrar;
    public javax.swing.JLabel lbl_comprobado;
    public javax.swing.JLabel lbl_mensaje;
    public javax.swing.JPanel pn_barra;
    public javax.swing.JPanel pn_fondo;
    public javax.swing.JTextField txt_texto;
    // End of variables declaration//GEN-END:variables
}
